### ISSUE TITLE
Trying to run patientor on Windows with npm start fails

### ISSUE THREAD

**Issue by teppolei** [fullstack-hy2020/patientor#19]
Trying to run npm start gives error, choking about lack of chokidar.
As for Chokidar, trying to run npm install chokidar throws a conniption and refuses to install, since theinstall package from npm only supports Darwin OSX.

How does one ensure that the front-end package works on Win32 (x64) architecture?

C:\FullStackOpen-course\part9\patientor>npm start

> patientor@0.1.0 start
> react-scripts start

i ｢wds｣: Project is running at http://172.18.64.1/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\FullStackOpen-course\part9\patientor\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\chokidar.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\DirectoryWatcher.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\watcherManager.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\watchpack.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\node\NodeWatchFileSystem.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\webpack.js
- C:\FullStackOpen-course\part9\patientor\node_modules\react-scripts\scripts\start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\chokidar.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\DirectoryWatcher.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\watcherManager.js
- C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\watchpack.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\node\NodeWatchFileSystem.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js
- C:\FullStackOpen-course\part9\patientor\node_modules\webpack\lib\webpack.js
- C:\FullStackOpen-course\part9\patientor\node_modules\react-scripts\scripts\start.js

    at Object.<anonymous> (C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\FullStackOpen-course\part9\patientor\node_modules\watchpack\lib\DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)

**Comment by teppolei** [comment]
Wrong version of course and current version had a workaround.
